N_BINS = 32
EXAMPLE_IMG_PATH = r'D:\Dokumenty\CBIR\CorelDB\pl_flower\84012.jpg'
SEARCH_DIRECTORY_ML = r'D:\Dokumenty\CBIR\CorelDBML'
SEARCH_DIRECTORY_C = r'D:\Dokumenty\CBIR\CorelDB'
RESULT_IMAGE_PATH = r'D:\Dokumenty\CBIR\repo_scripts\CBIRSolver\test_result\result_img.png'  # noqa
SEARCH_DIRECTORY_C_TAM = r'D:\Dokumenty\CBIR\CorelDBthinTamura'
SEARCH_DIRECTORY_THIN_SIFT = r'D:\Dokumenty\CBIR\CorelDBthinSIFT'
SEARCH_DIRECTORY_THIN_SIFT_2 = r'D:\Dokumenty\CBIR\CorelDBthinSIFT2'
SEARCH_DIRECTORY_THIN_HIST_NORM = r'D:\Dokumenty\CBIR\CorelDBthinNormHist'
SEARCH_DIRECTORY_THIN_HIST_EQUAL = r'D:\Dokumenty\CBIR\CorelDBthinEqualHist'
SEARCH_DIRECTORY_THIN_HIST_EQUAL_GRAY = r'D:\Dokumenty\CBIR\CorelDBthinEqualHistGray'
SEARCH_DIRECTORY_THIN_HIST_EQUAL_CLAHE = r'D:\Dokumenty\CBIR\CorelDBthinEqualCLAHEHist'
SEARCH_DIRECTORY_THIN_HIST_EQUAL_CLAHE_GRAY = r'D:\Dokumenty\CBIR\CorelDBthinEqualCLAHEHistGray'
